<a href="https://colab.research.google.com/github/VannisaLaowongkot/Road-Accident-Risk-Prediction-Project/blob/main/2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
url =  "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/4d919e5b-aa06-4fe4-8a13-5571747a1254/download/accident2019.csv"
df = pd.read_csv(url)
df.head()

/tmp/ipykernel_1308/1664995658.py:3: DtypeWarning: Columns (1,2,3,4,5,6,8,9,10,11,12,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
0,2019.0,1/1/2019,0:00,2/1/2019,6:11,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 21 (กม.ที่ 31+000) - บ้านวัง...,4.00,ลพบุรี,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,2.0,แจ่มใส,14.959105,100.873463
1,2019.0,1/1/2019,0:03,20/2/2020,13:48,กรมทางหลวง,เดชอุดม - อุบลราชธานี,419.77,อุบลราชธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,2.0,แจ่มใส,15.210738,104.862689
2,2019.0,1/1/2019,0:05,1/1/2019,10:35,กรมทางหลวง,ปราณบุรี - ปากน้ำปราณ,1.70,ประจวบคีรีขันธ์,รถจักรยานยนต์,ทางโค้งกว้าง+ที่ลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง),2.0,1.0,0.0,แจ่มใส,12.374259,99.907949
3,2019.0,1/1/2019,0:20,2/1/2019,5:12,กรมทางหลวงชนบท,เชื่อมทางหลวงหมายเลข 1013 (กม.ที่ 8+200) - บ้า...,1.88,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,1.0,แจ่มใส,18.601721,98.804204
4,2019.0,1/1/2019,0:25,4/1/2019,9:42,กรมทางหลวง,เกยไชย - ศรีมงคล,68.80,นครสวรรค์,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,0.0,แจ่มใส,15.866389,100.590010

In [3]:
print(df.shape)

(40246, 19)

In [4]:
df.columns.to_list()

['ปีที่เกิดเหตุ',
 'วันที่เกิดเหตุ',
 'เวลา',
 'วันที่รายงาน',
 'เวลาที่รายงาน',
 'หน่วยงาน',
 'สายทาง',
 'ก.ม.',
 'จังหวัด',
 'รถคันที่ 1',
 'บริเวณที่เกิดเหตุ/ลักษณะทาง',
 'มูลเหตุสันนิษฐาน',
 'ลักษณะการเกิดอุบัติเหตุ',
 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)',
 'จำนวนผู้เสียชีวิต',
 'รวมจำนวนผู้บาดเจ็บ',
 'สภาพอากาศ',
 'LATITUDE',
 'LONGITUDE']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40246 entries, 0 to 40245
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ปีที่เกิดเหตุ                     19194 non-null  float64
 1   วันที่เกิดเหตุ                    19194 non-null  object
 2   เวลา                              19194 non-null  object
 3   วันที่รายงาน                      19194 non-null  object
 4   เวลาที่รายงาน                     19194 non-null  object
 5   หน่วยงาน                          19194 non-null  object
 6   สายทาง                            19152 non-null  object
 7   ก.ม.                              19104 non-null  float64
 8   จังหวัด                           19183 non-null  object
 9   รถคันที่ 1                        19152 non-null  object
 10  บริเวณที่เกิดเหตุ/ลักษณะทาง       17659 non-null  object
 11  มูลเหตุสันนิษฐาน                  19137 non-null  object
 12  ลักษณะการเกิดอุบัติเหตุ           19144 non-null  object
 13  จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)  19194 non-null  float64
 14  จำนวนผู้เสียชีวิต                 19194 non-null  float64
 15  รวมจำนวนผู้บาดเจ็บ                19194 non-null  float64
 16  สภาพอากาศ                         19194 non-null  object
 17  LATITUDE                          19188 non-null  float64
 18  LONGITUDE                         19188 non-null  float64
dtypes: float64(7), object(12)
memory usage: 5.8+ MB

In [6]:
print(df.columns.tolist())

['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'วันที่รายงาน', 'เวลาที่รายงาน', 'หน่วยงาน', 'สายทาง', 'ก.ม.', 'จังหวัด', 'รถคันที่ 1', 'บริเวณที่เกิดเหตุ/ลักษณะทาง', 'มูลเหตุสันนิษฐาน', 'ลักษณะการเกิดอุบัติเหตุ', 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)', 'จำนวนผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ', 'สภาพอากาศ', 'LATITUDE', 'LONGITUDE']

In [7]:
missing_count = df.isnull().sum()
display(missing_count[missing_count > 0])

ปีที่เกิดเหตุ                       21052
วันที่เกิดเหตุ                      21052
เวลา                                21052
วันที่รายงาน                        21052
เวลาที่รายงาน                       21052
หน่วยงาน                            21052
สายทาง                              21094
ก.ม.                                21142
จังหวัด                             21063
รถคันที่ 1                          21094
บริเวณที่เกิดเหตุ/ลักษณะทาง         22587
มูลเหตุสันนิษฐาน                    21109
ลักษณะการเกิดอุบัติเหตุ             21102
จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)    21052
จำนวนผู้เสียชีวิต                   21052
รวมจำนวนผู้บาดเจ็บ                  21052
สภาพอากาศ                           21052
LATITUDE                            21058
LONGITUDE                           21058
dtype: int64

In [8]:
df.head(40246)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
0,2019.0,1/1/2019,0:00,2/1/2019,6:11,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 21 (กม.ที่ 31+000) - บ้านวัง...,4.00,ลพบุรี,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,2.0,แจ่มใส,14.959105,100.873463
1,2019.0,1/1/2019,0:03,20/2/2020,13:48,กรมทางหลวง,เดชอุดม - อุบลราชธานี,419.77,อุบลราชธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,2.0,แจ่มใส,15.210738,104.862689
2,2019.0,1/1/2019,0:05,1/1/2019,10:35,กรมทางหลวง,ปราณบุรี - ปากน้ำปราณ,1.70,ประจวบคีรีขันธ์,รถจักรยานยนต์,ทางโค้งกว้าง+ที่ลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง),2.0,1.0,0.0,แจ่มใส,12.374259,99.907949
3,2019.0,1/1/2019,0:20,2/1/2019,5:12,กรมทางหลวงชนบท,เชื่อมทางหลวงหมายเลข 1013 (กม.ที่ 8+200) - บ้า...,1.88,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,อื่นๆ,1.0,0.0,1.0,แจ่มใส,18.601721,98.804204
4,2019.0,1/1/2019,0:25,4/1/2019,9:42,กรมทางหลวง,เกยไชย - ศรีมงคล,68.80,นครสวรรค์,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,0.0,แจ่มใส,15.866389,100.590010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df = df.dropna(how="all")
print("จำนวนแถวหลังลบ:", len(df))
display(df.tail())

จำนวนแถวหลังลบ: 19194

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
19189,2019.0,31/12/2019,23:30,19/2/2020,14:22,กรมทางหลวง,ทางเข้าสังขละบุรี,1.25,กาญจนบุรี,รถปิคอัพบรรทุก 4 ล้อ,ทางโค้งกว้าง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,1.0,1.0,0.0,แจ่มใส,15.171119,98.462388
19190,2019.0,31/12/2019,23:35,1/1/2020,0:47,กรมทางหลวง,ปากน้ำกระบี่ - เขาทอง,14.66,กระบี่,รถจักรยานยนต์,NaN,ไม่ยอมให้รถที่มีสิทธิ์ไปก่อน,ชนท้าย,2.0,0.0,2.0,แจ่มใส,8.092608,98.811692
19191,2019.0,31/12/2019,23:40,1/1/2020,6:44,กรมทางหลวงชนบท,ถนนสมโภชเชียงใหม่ 700 ปี,5.60,เชียงใหม่,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,ชนท้าย,2.0,1.0,0.0,แจ่มใส,18.829234,99.006029
19192,2019.0,31/12/2019,23:40,1/1/2020,9:29,กรมทางหลวง,กระบุรี - หงาว,601.12,ระนอง,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,2.0,0.0,มีหมอก/ควัน/ฝุ่น,9.939225,98.633500
19193,2019.0,31/12/2019,23:45,3/1/2020,11:01,กรมทางหลวง,บางพลี - บางบ่อ,22.00,สมุทรปราการ,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนสิ่งกีดขวาง (บนผิวจราจร),2.0,1.0,0.0,แจ่มใส,13.588040,100.788317

In [10]:
missing_count = df.isnull().sum()
display(missing_count[missing_count > 0].sort_values(ascending=False))

บริเวณที่เกิดเหตุ/ลักษณะทาง    1535
ก.ม.                             90
มูลเหตุสันนิษฐาน                 57
ลักษณะการเกิดอุบัติเหตุ          50
สายทาง                           42
รถคันที่ 1                       42
จังหวัด                          11
LATITUDE                          6
LONGITUDE                         6
dtype: int64

In [11]:
rows_with_missing = df[df.isnull().any(axis=1)]
display(rows_with_missing.head(10))

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,วันที่รายงาน,เวลาที่รายงาน,หน่วยงาน,สายทาง,ก.ม.,จังหวัด,รถคันที่ 1,บริเวณที่เกิดเหตุ/ลักษณะทาง,มูลเหตุสันนิษฐาน,ลักษณะการเกิดอุบัติเหตุ,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,สภาพอากาศ,LATITUDE,LONGITUDE
6,2019.0,1/1/2019,0:30,25/10/2019,14:25,กรมทางหลวง,ท่าทอง - สวนสมบูรณ์,65.850,ชุมพร,รถปิคอัพบรรทุก 4 ล้อ,NaN,ไม่ยอมให้รถที่มีสิทธิ์ไปก่อน,ชนเป็นมุมบริเวณทางแยก,2.0,0.0,2.0,แจ่มใส,9.949354,99.063479
20,2019.0,1/1/2019,1:30,4/1/2019,11:56,กรมทางหลวง,ขุนตาน - อุโมงค์,508.365,ลำพูน,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,1.0,0.0,0.0,มีหมอก/ควัน/ฝุ่น,18.465851,99.149981
44,2019.0,1/1/2019,3:00,2/1/2019,22:31,กรมทางหลวง,เมืองภูเก็ต - กะทู้,1.148,ภูเก็ต,รถจักรยานยนต์,NaN,ขับรถเร็วเกินอัตรากำหนด,ชนท้าย,2.0,0.0,1.0,แจ่มใส,7.893418,98.365762
46,2019.0,1/1/2019,3:00,29/3/2019,8:22,กรมทางหลวง,ราษฎร์บูรณะ - พระสมุทรเจดีย์,21.600,สมุทรปราการ,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,ฝ่าฝืนสัญญาณไฟ/เครื่องหมายจราจร,ชนเป็นมุมบริเวณทางแยก,2.0,0.0,0.0,แจ่มใส,13.594435,100.579662
47,2019.0,1/1/2019,3:05,1/1/2019,3:05,การทางพิเศษแห่งประเทศไทย,บางพลี-สุขสวัสดิ์,NaN,กรุงเทพมหานคร,NaN,อื่นๆ,NaN,NaN,1.0,0.0,1.0,แจ่มใส,13.790529,100.610702
51,2019.0,1/1/2019,3:20,20/2/2019,13:50,กรมทางหลวง,ทางเลี่ยงเมืองลพบุรี,5.350,ลพบุรี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,0.0,แจ่มใส,14.755132,100.650934
52,2019.0,1/1/2019,3:30,5/1/2019,11:00,กรมทางหลวง,แยกโพธารส - ท่ายาง,2.350,ชุมพร,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,1.0,0.0,1.0,แจ่มใส,10.486153,99.194186
53,2019.0,1/1/2019,3:30,9/10/2019,15:57,กรมทางหลวง,สองพี่น้อง - มะขามล้ม,11.600,สุพรรณบุรี,รถปิคอัพบรรทุก 4 ล้อ,NaN,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,1.0,0.0,0.0,แจ่มใส,14.238329,100.042807
58,2019.0,1/1/2019,4:25,11/6/2019,9:32,กรมทางหลวง,ท่าชี - ถ้ำพรรณรา,225.532,สุราษฎร์ธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,NaN,คน/รถ/สัตว์ตัดหน้ากระชั้นชิด,ชนท้าย,2.0,0.0,3.0,แจ่มใส,8.629675,99.352289
81,2019.0,1/1/2019,5:42,1/1/2019,5:42,การทางพิเศษแห่งประเทศไทย,บางนา-ชลบุรี,NaN,กรุงเทพมหานคร,อื่นๆ,ทางตรง,NaN,NaN,1.0,0.0,0.0,แจ่มใส,13.790529,100.610702

In [12]:
df_clean = df.copy()
columns_to_drop = [
    "วันที่รายงาน",
    "เวลาที่รายงาน",
    "หน่วยงาน",
    "บริเวณที่เกิดเหตุ/ลักษณะทาง",
    "มูลเหตุสันนิษฐาน",
    "ลักษณะการเกิดอุบัติเหตุ",
    "สภาพอากาศ",
    "รถคันที่ 1"
    ]

df_clean = df_clean.drop(columns=columns_to_drop)
print("จำนวนแถวและคอลัมน์หลังลบ:", df_clean.shape)
print("คอลัมน์ที่เหลือ:")
print(df_clean.columns.tolist())

จำนวนแถวและคอลัมน์หลังลบ: (19194, 11)
คอลัมน์ที่เหลือ:
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'ก.ม.', 'จังหวัด', 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)', 'จำนวนผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ', 'LATITUDE', 'LONGITUDE']

In [13]:
missing_count = df_clean.isnull().sum()
display(missing_count[missing_count > 0].sort_values(ascending=False))

ก.ม.         90
สายทาง       42
จังหวัด      11
LATITUDE      6
LONGITUDE     6
dtype: int64

In [15]:
rows_with_missing_clean = df_clean[df.isnull().any(axis=1)]
display(rows_with_missing_clean.head(10))

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,สายทาง,ก.ม.,จังหวัด,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,LATITUDE,LONGITUDE
6,2019.0,1/1/2019,0:30,ท่าทอง - สวนสมบูรณ์,65.850,ชุมพร,2.0,0.0,2.0,9.949354,99.063479
20,2019.0,1/1/2019,1:30,ขุนตาน - อุโมงค์,508.365,ลำพูน,1.0,0.0,0.0,18.465851,99.149981
44,2019.0,1/1/2019,3:00,เมืองภูเก็ต - กะทู้,1.148,ภูเก็ต,2.0,0.0,1.0,7.893418,98.365762
46,2019.0,1/1/2019,3:00,ราษฎร์บูรณะ - พระสมุทรเจดีย์,21.600,สมุทรปราการ,2.0,0.0,0.0,13.594435,100.579662
47,2019.0,1/1/2019,3:05,บางพลี-สุขสวัสดิ์,NaN,กรุงเทพมหานคร,1.0,0.0,1.0,13.790529,100.610702
51,2019.0,1/1/2019,3:20,ทางเลี่ยงเมืองลพบุรี,5.350,ลพบุรี,1.0,0.0,0.0,14.755132,100.650934
52,2019.0,1/1/2019,3:30,แยกโพธารส - ท่ายาง,2.350,ชุมพร,1.0,0.0,1.0,10.486153,99.194186
53,2019.0,1/1/2019,3:30,สองพี่น้อง - มะขามล้ม,11.600,สุพรรณบุรี,1.0,0.0,0.0,14.238329,100.042807
58,2019.0,1/1/2019,4:25,ท่าชี - ถ้ำพรรณรา,225.532,สุราษฎร์ธานี,2.0,0.0,3.0,8.629675,99.352289
81,2019.0,1/1/2019,5:42,บางนา-ชลบุรี,NaN,กรุงเทพมหานคร,1.0,0.0,0.0,13.790529,100.610702

In [17]:
missing_latitude = df_clean[df_clean["LATITUDE"].isnull()]
display(missing_latitude)

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,สายทาง,ก.ม.,จังหวัด,จำนวนรถที่เกิดเหตุ (รวมคันที่ 1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ,LATITUDE,LONGITUDE
501,2019.0,2/1/2019,21:30,แยกทางหลวงหมายเลข 9 (กม.ที่ 43+490) - อำเภอไทร...,3.00,NaN,2.0,0.0,2.0,NaN,NaN
7643,2019.0,7/5/2019,3:15,แยกทางหลวงหมายเลข 317 (กม.ที่ 10+100) - บ้านทุ...,4.95,NaN,1.0,0.0,0.0,NaN,NaN
8039,2019.0,15/5/2019,11:45,แยกทางหลวงหมายเลข 1 (กม.ที่ 123+400) - บ้านสองคอน,11.90,NaN,2.0,0.0,4.0,NaN,NaN
8044,2019.0,15/5/2019,13:50,แยกทางหลวงหมายเลข 416 (กม.ที่ 6+250) -บ้านคลอง...,3.10,NaN,2.0,0.0,2.0,NaN,NaN
11279,2019.0,1/8/2019,8:00,แยกทางหลวงหมายเลข 22 (กม.ที่ 235+225) - บ้านรา...,0.80,NaN,2.0,0.0,1.0,NaN,NaN
17957,2019.0,28/12/2019,2:30,แยกทางหลวงหมายเลข 2418 (กม.ที่ 21+600) - บ้านบ...,2.35,NaN,1.0,0.0,1.0,NaN,NaN

In [18]:
df_clean = df_clean.dropna(subset=["LATITUDE"])
missing_count = df_clean.isnull().sum()
display(missing_count[missing_count > 0].sort_values(ascending=False))

ก.ม.       90
สายทาง     42
จังหวัด     5
dtype: int64

In [19]:
urls = {
    2019: "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/4d919e5b-aa06-4fe4-8a13-5571747a1254/download/accident2019.csv",
    2020: "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/40476c7b-4194-4dc2-aba5-7326819ed071/download/accident2020.csv",
    2021: "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/d0a8601a-3ee5-4ce8-8e9d-3dae3915dc30/download/accident2021.csv",
    2022: "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/733b7874-bd5f-44b9-b271-650890b061f2/download/accident2022.csv",
    2023: "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/661f2ead-1f28-4cd9-8a67-1bef76b33ef6/download/accident2023.csv",
    2024: "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/83e9fae0-5f33-45e7-9a6d-6d5ad2060a08/download/accident2024.csv",
    2025: "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/e1db5e93-2b70-4ee4-b6d7-7ead76d14a09/download/accident2025.csv",
    2026: "https://datagov.mot.go.th/dataset/7e077ffd-dc4f-4dc6-a71c-0813726f3c12/resource/4625b7aa-99a4-4dfb-9a0f-6402814d0f2c/download/accident2026.csv"
}

In [45]:
def clean_accident_data(df):

    df = df.dropna(how="all").copy()


    columns_to_drop = [
        "วันที่รายงาน",
        "เวลาที่รายงาน",
        "หน่วยงาน",
        "บริเวณที่เกิดเหตุ/ลักษณะทาง",
        "มูลเหตุสันนิษฐาน",
        "ลักษณะการเกิดอุบัติเหตุ",
        "สภาพอากาศ",
        "รถคันที่ 1",
        "ACC_CODE",
        "สายทางหน่วยงาน",
        "รหัสสายทาง",
        "รถคันที่1",
        "บริเวณที่เกิดเหตุ",
        "ลักษณะการเกิดเหตุ",
        "รถบรรทุก6ล้อ",
        "รถบรรทุกไม่เกิน10ล้อ",
        "รถบรรทุกมากกว่า10ล้อ",
        "รถอีแต๋น",
        "รถอื่นๆ",
        "คนเดินเท้า",
        "ผู้บาดเจ็บเล็กน้อย",
        "ผู้บาดเจ็บสาหัส",
        "รถจักรยานยนต์",
        "รถสามล้อเครื่อง",
        "รถยนต์นั่งส่วนบุคคล",
        "รถตู้",
        "รถปิคอัพโดยสาร",
        "รถโดยสารมากกว่า4ล้อ",
        "รถปิคอัพบรรทุก4ล้อ",
        "รถและคนที่เกิดเหตุ",
        "จำนวนที่เกิดเหตุทั้งหมด(รวมคนเดินเท้า)",
        "รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ",
        "รถบรรทุกมากกว่า6ล้อไม่เกิน10ล้อ",
        "รถบรรทุกมากกว่า10ล้อ(รถพ่วง)",
        "อื่นๆ",
        "จำนวนผู้บาดเจ็บสาหัส",
        "จำนวนผู้บาดเจ็บเล็กน้อย",
        "บริเวณที่เกิดเหตุอื่น"
]

    df = df.drop(
        columns=columns_to_drop,
        errors="ignore"
    )

    df = df.dropna(
        subset=["LATITUDE", "LONGITUDE"]
    ).copy()

    return df

In [46]:
cleaned_data = {}

for year, url in urls.items():
    print(f"กำลัง Clean ข้อมูลปี {year}...")


    df = pd.read_csv(url)


    df_clean = clean_accident_data(df)


    cleaned_data[year] = df_clean

    print(f"ปี {year}: เหลือ {len(df_clean):,} แถว")

print("Clean ข้อมูลครบทุกปีแล้ว")

กำลัง Clean ข้อมูลปี 2019...

/tmp/ipykernel_1308/1865890183.py:7: DtypeWarning: Columns (1,2,3,4,5,6,8,9,10,11,12,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

ปี 2019: เหลือ 19,188 แถว
กำลัง Clean ข้อมูลปี 2020...
ปี 2020: เหลือ 21,175 แถว
กำลัง Clean ข้อมูลปี 2021...
ปี 2021: เหลือ 19,997 แถว
กำลัง Clean ข้อมูลปี 2022...
ปี 2022: เหลือ 20,493 แถว
กำลัง Clean ข้อมูลปี 2023...
ปี 2023: เหลือ 23,665 แถว
กำลัง Clean ข้อมูลปี 2024...
ปี 2024: เหลือ 23,714 แถว
กำลัง Clean ข้อมูลปี 2025...
ปี 2025: เหลือ 23,546 แถว
กำลัง Clean ข้อมูลปี 2026...
ปี 2026: เหลือ 17,290 แถว
Clean ข้อมูลครบทุกปีแล้ว

In [47]:
for year, df_clean in cleaned_data.items():
    print(
        f"ปี {year}: "
        f"{df_clean.shape[0]:,} แถว, "
        f"{df_clean.shape[1]} คอลัมน์"
    )

ปี 2019: 19,188 แถว, 11 คอลัมน์
ปี 2020: 21,175 แถว, 11 คอลัมน์
ปี 2021: 19,997 แถว, 11 คอลัมน์
ปี 2022: 20,493 แถว, 11 คอลัมน์
ปี 2023: 23,665 แถว, 11 คอลัมน์
ปี 2024: 23,714 แถว, 11 คอลัมน์
ปี 2025: 23,546 แถว, 11 คอลัมน์
ปี 2026: 17,290 แถว, 11 คอลัมน์

In [27]:
display(cleaned_data[2025].head(100))

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,สายทาง,KM,จังหวัด,LATITUDE,LONGITUDE,รถที่เกิดเหตุ,รถและคนที่เกิดเหตุ,ผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ
0,2025,45658,0:00,NaN,50.832,อยุธยา,14.469469,100.548894,2,2,0,1
1,2025,45658,0:01,เนินโมก - แปลงยาว,88.200,ชลบุรี,13.397186,101.281177,1,1,0,0
2,2025,45658,0:01,แยกทางหลวงหมายเลข 404 (กม.ที่ 93+100) - บ้านสะ...,13.500,สตูล,6.988392,99.846703,1,1,0,1
3,2025,45658,0:03,จุดเชื่อมต่อสะพานภูมิพลที่ 1 เข้าถนนวงแหวนอุตส...,0.666,สมุทรปราการ,13.664350,100.535430,2,2,0,1
4,2025,45658,0:03,แยกสะแกกรัง - เขาพะแวง,7.515,อุทัยธานี,15.452032,100.021930,2,2,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025,45658,11:30,NaN,4.135,สิงห์บุรี,14.853856,100.379935,2,2,0,0
96,2025,45658,11:30,แขวงคลองสองต้นนุ่น - พิมพา,11.300,กรุงเทพมหานคร,13.729516,100.743579,2,2,0,0
97,2025,45658,11:45,อ่างทอง - ปากดง,10.080,อ่างทอง,14.656077,100.412001,2,2,0,1
98,2025,45658,11:50,บ้านวังขอน - ท่าช้าง,20.985,สิงห์บุรี,14.930202,100.270134,2,2,0,1
99,2025,45658,11:50,พระประแดง - บางแค,15.450,กรุงเทพมหานคร,13.639648,100.412158,3,3,0,1

In [34]:
cleaned_data[2025]['รถที่เกิดเหตุ'].equals(
    cleaned_data[2025]['รถและคนที่เกิดเหตุ']
)

False

In [35]:
df = cleaned_data[2025]

different = ~(
    df['รถที่เกิดเหตุ'].eq(df['รถและคนที่เกิดเหตุ']) |
    (df['รถที่เกิดเหตุ'].isna() & df['รถและคนที่เกิดเหตุ'].isna())
)

print("จำนวนแถวที่แตกต่างกัน:", different.sum())

จำนวนแถวที่แตกต่างกัน: 252

In [36]:
df = cleaned_data[2025]

display(df[
    ~(df['รถที่เกิดเหตุ'].eq(df['รถและคนที่เกิดเหตุ']) |
      (df['รถที่เกิดเหตุ'].isna() & df['รถและคนที่เกิดเหตุ'].isna()))
])

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,สายทาง,KM,จังหวัด,LATITUDE,LONGITUDE,รถที่เกิดเหตุ,รถและคนที่เกิดเหตุ,ผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ
50,2025,45658,5:00,ตรัง - บ้านนา,21.680,ตรัง,7.367962,99.677000,1,2,0,2
61,2025,45658,6:50,วังน้อย - บ้านสร้าง,5.680,อยุธยา,14.273301,100.683767,1,2,0,2
185,2025,45658,17:40,NaN,133.150,มุกดาหาร,16.594495,104.427949,1,2,0,1
193,2025,45658,18:23,นิคมเชียงพิณ - หนองบัวลำภู,14.100,อุดรธานี,17.315245,102.642229,1,2,0,1
196,2025,45658,18:30,ดอยสะเก็ด - ป่าบง,9.090,เชียงใหม่,18.796535,99.107360,1,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
23665,2025,46022,18:50,อ่างทอง - ไชโย,56.811,อ่างทอง,14.638373,100.474292,1,2,1,0
23667,2025,46022,19:00,ตลิ่งชัน - ดงขุย,51.225,เพชรบูรณ์,16.117002,100.741287,1,2,0,1
23672,2025,46022,19:30,หนองคู - ดงบัง,23.500,มหาสารคาม,15.653810,103.254061,1,2,1,0
23694,2025,46022,21:54,แยกทางหลวงหมายเลข 346 (กม.ที่ 47+500) - บ้านศา...,20.500,นครปฐม,13.863498,100.296803,2,3,0,1
23695,2025,46022,21:59,ทางต่างระดับคีรี - ทางต่างระดับหนองข้างคอก,0.500,ชลบุรี,13.303005,100.993911,1,2,0,2

In [44]:
display(cleaned_data[2026].head(100))

,ปีที่เกิดเหตุ,วันที่เกิดเหตุ,เวลา,สายทาง,ก.ม.,จังหวัด,บริเวณที่เกิดเหตุอื่น,LATITUDE,LONGITUDE,จำนวนรถที่เกิดเหตุ(รวมคันที่1),จำนวนผู้เสียชีวิต,รวมจำนวนผู้บาดเจ็บ
0,2026.0,1/1/2026,0:01,นิคมคำสร้อย - หนองสูง,1.150,มุกดาหาร,ทางตรง+ที่ราบ,16.381335,104.544672,2.0,1.0,2.0
1,2026.0,1/1/2026,0:03,พญาเย็น - นครราชสีมา,139.700,นครราชสีมา,ทางยกระดับ+ที่ราบ,14.853079,101.578627,1.0,0.0,1.0
2,2026.0,1/1/2026,0:05,บ้านโป่ง - พร้าว,34.800,เชียงใหม่,ทางตรง+ที่ราบ,19.089352,98.989752,2.0,1.0,1.0
3,2026.0,1/1/2026,0:10,บ้านหว้า - อุทัย,8.050,พระนครศรีอยุธยา,ทางแยกรูปตัว ++ที่ราบ,14.324264,100.652160,2.0,0.0,1.0
4,2026.0,1/1/2026,0:10,แยกทางหลวงหมายเลข 409 (กม.ที่ 7+204) - น้ำตกทร...,2.000,ปัตตานี,ทางตรง+ไม่มีความลาดชัน/ที่ราบ,6.676034,101.128955,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
96,2026.0,1/1/2026,8:20,พิมพา - หนองข้างคอก,56.000,ชลบุรี,ทางโค้งปกติ+ที่ราบ,13.496046,101.045322,1.0,0.0,0.0
97,2026.0,1/1/2026,8:30,แยกทางหลวงหมายเลข 1148 (กม.ที่ 95+225) - โครงก...,50.350,พะเยา,ทางตรง+ไม่มีความลาดชัน/ที่ราบ,19.420537,100.419427,1.0,0.0,1.0
98,2026.0,1/1/2026,8:32,ท่ากกแดง - บึงกาฬ,125.737,บึงกาฬ,ทางโค้งปกติ+ที่ราบ,18.344155,103.639471,1.0,1.0,0.0
99,2026.0,1/1/2026,8:40,แยกทางหลวงหมายเลข 22 (กม.ที่ 172+690) - บ้านดง...,20.780,สกลนคร,ทางตรง+ไม่มีความลาดชัน/ที่ราบ,17.153213,104.338022,1.0,0.0,1.0
100,2026.0,1/1/2026,8:50,ห้วยไคร้ - ห้วยน้ำริน,42.167,เชียงราย,ทางแยกรูปตัว ++ที่ราบ,20.423892,99.876784,2.0,0.0,2.0

In [48]:
for year in range(2019, 2027):
    print(f"\nปี {year}")
    print(cleaned_data[year].columns.tolist())

ปี 2019
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'ก.ม.', 'จังหวัด', 'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)', 'จำนวนผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ', 'LATITUDE', 'LONGITUDE']

ปี 2020
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2021
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2022
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2023
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2024
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2025
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2026
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'ก.ม.', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'จำนวนรถที่เกิดเหตุ(รวมคันที่1)', 'จำนวนผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

In [53]:
rename_columns = {
    'ก.ม.': 'KM',
    'จำนวนรถที่เกิดเหตุ (รวมคันที่ 1)': 'รถที่เกิดเหตุ',
    'จำนวนผู้เสียชีวิต': 'ผู้เสียชีวิต',
    'จำนวนรถที่เกิดเหตุ(รวมคันที่1)': 'รถที่เกิดเหตุ'
}

for year in range(2019, 2027):
    cleaned_data[year] = cleaned_data[year].rename(
        columns=rename_columns
    )

In [54]:
for year in range(2019, 2027):
    print(f"\nปี {year}")
    print(cleaned_data[year].columns.tolist())

ปี 2019
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ', 'LATITUDE', 'LONGITUDE']

ปี 2020
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2021
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2022
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2023
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2024
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2025
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

ปี 2026
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']

In [55]:
column_order = cleaned_data[2020].columns.tolist()
for year in [2019, 2026]:
    cleaned_data[year] = cleaned_data[year][column_order]

In [56]:
print(cleaned_data[2019].columns.tolist())
print(cleaned_data[2020].columns.tolist())
print(cleaned_data[2026].columns.tolist())

['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']
['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'สายทาง', 'KM', 'จังหวัด', 'LATITUDE', 'LONGITUDE', 'รถที่เกิดเหตุ', 'ผู้เสียชีวิต', 'รวมจำนวนผู้บาดเจ็บ']